import { Song } from "./songs_data";

export const SONGS_OTHER: Song[] = [
  {
    id: 301,
    title: "AMAZING GRACE",
    category: "Knananuk Inglês",
    section: "General Hymns",
    verses: [
      "1. Amazing grace, how sweet the sound, that saved a wretch like me.",
      "2. I once was lost but now am found, was blind but now I see.",
    ],
  },
  {
    id: 402,
    title: "ADAKAH TEMPAT DI HATIMU",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "Solo: Adakah tempat di hatimu untuk firman",
      "Koor: Rahmat dan kasih Tuhan bagimu terpancar lewat sabda",
      "Solo: Adakah waktu di hidupmu untuk merenungkan Tuhan.",
      "Koor: Alangkah dalam makna sabda Allah di dalam kehidupan.",
      "O padukanlah budimu dengan hatimu",
      "Dengarkan bisikan Nya apa makna hidupmu.",
      "Solo: Mengapa Dikau yang kuasa, sudi mendatangi aku",
      "Koor: Membawa warta keselamatan bahagia hidup kekal.",
      "(NB. Sesudah hidup kekal pertama ada interlude lalu solo awal s/d lewat sabda, lalu final.)",
    ],
  },
  {
    id: 403,
    title: "ANGKATLAH MATAMU",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Angkatlah matamu, pandanglah daun-daun bergetar diterpa angin musim.",
      "Adakah hatimu juga turut bergetar mendengar panggilan Tuhan Yesus?",
      "Yesus, Tuhanku, kepada siapa aku akan pergi. Yesus, Tuhanku, hanya Engkau harapan hidupku.",
      "2. Lihatlah di ladang kembang bakung tersenyum, menyapa sinar mentari pagi;",
      "Adakah hatimu menyatu dalam kasih, menyambut tawaran cinta Yesus.",
    ],
  },
  {
    id: 404,
    title: "BAHASA CINTA",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Andaikan aku lakukan yang luhur mulia jika tanpa kasih cinta, hampa tak berguna.",
      "Ajarilah kami bahasa cintaMu agar kami dekat padaMu, ya Tuhanku (2x)",
      "2. Andaikan aku fahami bahasa semua, hanyalah bahasa cinta kunci tiap hati.",
    ],
  },
  {
    id: 405,
    title: "BETAPA HATIKU",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Betapa hatiku berterima kasih,",
      "Yesus, Kau mengasihiki; Kau memilikiku.",
      "Hanya ini, Tuhan, persembahanku:",
      "segenap hidupku, jiwa dan ragaku",
      `S'bab tak kumiliki harta kekayaan yang cukup berarti 'tuk kupersembahkan.`,
      "Hanya ini, Tuhan, permohonanku:",
      "terimalah, Tuhan, persembahanku.",
      "Pakailah hidupku sebagai alatMu seumur hidupku.",
      "2. Betapa hatiku berterima kasih,",
      "Yesus, Kau mengasihiki; Kau memilikiku.",
      "Hanya ini, Tuhan, persembahanku:",
      "segenap hidupku, kubawa padaMu",
      `S'bab tak kumiliki harta kekayaan yang cukup berarti 'tuk kupersembahkan.`,
      "Hanya ini, Tuhan, permohonanku:",
      "terimalah, Tuhan, persembahanku.",
      "Pakailah hidupku bagaikan bejana berguna bagiMu",
    ],
  },
  {
    id: 406,
    title: "BUNDA PENOLONG ABADI",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Pada wajahmu yang suci",
      "matamu nampak bening, sejuk, lembut",
      "Kau pandang pada abdimu berdoa,",
      "O Bunda, penolong abadi.",
      "Engkau pangku anakmu Yesus Putra Allah Sumber suka dan duka hatimu",
      "Hanya engkau sendirilah yang tahu",
      "Pahit dan manisnya hidupmu (2x)",
      "2. Bukannya kepadamu, O Bunda,",
      "pandangan penuh cintanya tertuju",
      "Salib dan tombak bengis dilihatnya,",
      "O Bunda, Penolong abadi.",
    ],
  },
  {
    id: 407,
    title: "HIMNE SSPS",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Dikau sang Tritungal Allah maha kudus,",
      "yang bertakhtah di hatiku sepanjang hayatku.",
      "Dikau sumber abadi di surga dan bumi.",
      "kualunkan madah indah, gemah iman dan kekal.",
      "Allah, akbar, o Tritunggal maha kudus, kusanjung dikau selamanya, kami abdi Roh yang kudus setia mengabdi Dikau sepanjang masa (2x)",
      "2. Kristus wujud cinta, Bapa maha agung",
      "lewat hati maha kudus,",
      "cinta Allah bersemi.",
      "Dikau Allah Roh Kudus karunia luhur bapa,",
      "penjiwa seluruh karyaku demi kerajaan surga.",
    ],
  },
  {
    id: 408,
    title: "HIMNE SANTO ARNOLDUS YANSSEN",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Nyanyikanlah lagu gembira diiringi musik nan merdu; Puji Tuhan dalam diri abdinya yang berjuang dalam hidupnya,",
      "mewartakan sabda ilahi, sabda kasih Bapa, Sabda abadi selamanya.",
      "Santo Arnoldus, Pendiri Srikat misi, Mohankan kami rahmat dari Allah agar teguh mengabdi.",
      "Kupasrahkan panggilan hidupku setia selamanya.",
      "2. Kasih Tuhan terpantul murni menyinari hati hambanya yang berpasrah penuh harap dan cinta seluruh diri dipersembahkan bagi Tuhan dan Gerejanya.",
      "Indahnya kasih Tuhan Agung membias tiada tara Santo Arnoldus Abdi Tuhan yang setia.",
      "Doakan kami, para pewarismu, meneruskan smangatmu: semoga kegelapan dunia terhalau oleh Sang Sabda.",
      `3. Iklas hati pasrahkan diri dalam cinta panggilan suci, mengikuti Yesus Sang Sabda Allah s'luruh dunia tanah misinya jadi ladang sabda ilahi.`,
      "Hiduplah hati Yesus di dalam hati manusia.",
      "SantoYoseph misionaris sejati terlukis indah dalam hati kami sepanjang hidup ini.",
      "Bantulah kami dengan doamu agar teguh mengabdi.",
      `4. Kupanjatkan syukur berlimpah ke hadirat Tuhan di surga atas cinta dan kasih setianya keluarga Arnoldus YANSSEN berkembanglah ke s'luruh dunia;`,
      "pancarkan kasih Tuhan, kasih ilahi selamanya.",
      "Santo Arnoldus, trimalah puji kami, ungkapan syukur sembah bakti kami puji kesetianmu.",
      "Hiduplah Allah Tritunggal Kudus, kini dan sepanjang masa.",
    ],
  },
  {
    id: 409,
    title: "KENANGKANLAH",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Kenangkan kisah kasih Tuhan dalam seluruh sejarah hidupmu.",
      "Pernahkah Tuhan tidak setia membimbing seluruh hidupmu?",
      "Agungkanlah Bapa maha penyayang, syukur bagi penebus dunia",
      "Kar'na Tuhan setia selalu; abadi kasih setiaNya.",
      "2. Kisahkan keagungan Tuhan dan wartakanlah kemuliaanNya",
      "Kepada semua makhluk hidup, kepada semua ciptaanNya.",
      "3. Tuhanlah gembala setia, Tuhan Allah-pun perisai hidupmu.",
      "Membimbing dan menuntun hidupmu, menjaga hidup yang abadi.",
    ],
  },
  {
    id: 410,
    title: "KUPERSEMBAHKAN",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Kupersembahkan kepada Tuhan seluruh hidupku",
      "segenap hatiku, jiwa dan ragaku.",
      "Kupasrah diri, karya dan bakti",
      "bersama roti anggur yang kini kusembahkan",
      "dalam perjamuan suci Ekaristi",
      "2. Trimalah, Bapa, syukur pujian,",
      "trima kasihku kar'na cintaMu, Tuhan.",
      "Sembah sujudku kepada Tuhan",
      "yang t'lah memanggil aku dalam karya yang agung",
      "karya keselamatan yang abadi.",
      "Berkatilah, ya Tuhan, darma bakti hidupku. untuk Gereja dan neg'riku.",
      "Coda: Kupersembahkan, kupersembahkan. (2x)",
    ],
  },
  {
    id: 411,
    title: "MARIA RATU IMAM",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Maria penuh rahmat,",
      "Ratu para Imam",
      "dampingi Imam kami",
      "dengan rahmat Allah.",
      "O Bunda Ratu Imam,",
      "doakan Imammu",
      "yang slalu dan snantiasa mengharap doamu.",
      "2. Ibunda Imam Agung Penebus",
      "Putramu dan Ratu para rasul serta pengiringnya.",
    ],
  },
  {
    id: 412,
    title: "SEBUTIR EMBUN",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Sebutir embun bening gemerlap bercahaya",
      "memantulkan terang ilahi",
      "Ketika malam tiba bintangpun bercahaya",
      "menerangi wajah semesta.",
      "2. Sebutir sabda Yesus bergema membahana,",
      "mewartakan kasih Tuhanku.",
      "Ketika hati risau diburu duka lara,",
      "sabda Tuhan terang jalanku.",
      "SabdaMu, ya Tuhanku, penuntun kehidupan yang membimbing hidup semesta.",
      "Musim silih berganti, sabdaMu tetap teguh menerangi jalan hidupku.",
    ],
  },
  {
    id: 413,
    title: "TUHANKU GEMBALAKU",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Tuhanku, gembalaku,",
      "aku dihantar olehNya",
      "ke padang rumput menghijau.",
      "Tuhanku gembalaku,",
      "tiada aku kekurangan,",
      "tiada aku kekurangan,",
      "Tuhanku gembalaku,",
      "tiada aku kekurangan,",
      "Tuhanku gembalaku,",
      "tiada aku kekurangan.",
      "2. Aku dihantar olehNya",
      "ke sumber sumber istirahat,",
      "disegarkanNya jiwaku.",
      "3. Biarku lewat jurang kelam,",
      "tiada kutakut bencana;",
      "Engkau menyertai daku.",
    ],
  },
  {
    id: 414,
    title: "TUHAN, GENGGAMLAH",
    category: "Knananuk Indonesia",
    section: "Default",
    verses: [
      "1. Tuhan, genggamlah tanganku yang hina,",
      "pimpinlah langkah kaki yang enggan melangkah,",
      "dalam ribaan kasihMu.",
      "Tuhan, Oh Tuhan,",
      "dengarlah keluh kesahku;",
      "indahkanlah ratap serta tangisku.",
      "Bawalah daku ke Sion, ke tempat Engkau berkanjang.",
      "2. Tuhan, kupinta ampuni dosaku,",
      "jangan indahkan segala kelalaianku.",
      "Tuhan dengarlah doaku.",
    ],
  },
  {
    id: 415,
    title: "BAWALAH DAKU KE SION",
    category: "Knananuk Indonesia",
    section: "Default",
    refrain:
      "Tuhan oh Tuhan dengarlah keluh kesahku. Indahkanlah ratap serta tangisku. Bawalah daku ke Sion, ke tempat Engkau berkanjang.",
    verses: [
      "Tuhan genggamlah tanganku yang hina.",
      "Pimpinlah langkah kaki yang enggan melangkah.",
      "Dalam ribaan kasih-Mu.",
      "Tuhan ku pinta ampuni dosaku.",
      "Jangan indahkan segala kelalaianku.",
      "Tuhan dengarlah doaku.",
    ],
  },
];
